// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aboupreneur-ads/AgriFoodBuyerDisconnect.tsx": () => import("../components/mockups/aboupreneur-ads/AgriFoodBuyerDisconnect.tsx"),
  "./components/mockups/aboupreneur-ads/HvacEmptyCalendar.tsx": () => import("../components/mockups/aboupreneur-ads/HvacEmptyCalendar.tsx"),
  "./components/mockups/aboupreneur-ads/NewcomerReferralCeiling.tsx": () => import("../components/mockups/aboupreneur-ads/NewcomerReferralCeiling.tsx"),
  "./components/mockups/aboupreneur-ads/PlumbingMissedCalls.tsx": () => import("../components/mockups/aboupreneur-ads/PlumbingMissedCalls.tsx")
};
